name: Auto Create PR from dev to master
on:
  schedule:
    # 每周四北京时间21点触发（UTC时间13点）
    - cron: '0 13 * * 4'
  workflow_dispatch: # 可选：支持手动触发

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: master  
          head: dev     
          title: "Weekly Auto-Merge: dev → master"
          body: "Automated PR created by GitHub Actions."
          labels: "automated" # 可选：添加标签
          token: ${{ secrets.GITHUB_TOKEN }} # 使用默认权限
