name: Auto Create PR from dev to master
on:
  schedule:
    # 每周四北京时间21点触发（UTC时间13点）
    - cron: '0 13 * * 4'
  workflow_dispatch: # 可选：支持手动触发

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # 拉取完整提交历史

      - run: git branch  cpr/dev-patch
      - run: git log cpr/dev-patch -n 20
      - run: git log master -n 20

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          branch: cpr/dev-patch
          title: "Weekly Auto-Merge: dev → master"
          body: "Automated PR created by GitHub Actions."
          labels: "automated"
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: git log dev -n 20
      - run: git log master -n 20
      - run: git log cpr/dev-patch -n 20
      - run: git rev-list --right-only --count master...cpr/dev-patch
